# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "node"

# http://docs.travis-ci.com/user/notifications/
notifications:
  email: false

# https://docs.travis-ci.com/user/deployment/npm/
deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: AxhfwgDSzBO/tKJ8pSRt+ultiwyDhOnFVBg2pOa8TBuiAVS6f4+H8GmLoZvmYXBG9z+2ZQQmN8USjhzIaZ3ZA1OflkZ1zAySOXoI6K/Q059XF8f/Pzm1GKjfPgxH85YYvu+5rgdWbkZequZOpJY/ZjAXQVXbMhveId+bRNUTS0Lq7+qtLarJxseIA01HeqwrPiB8CPvXKlNhA+DyuJVABDHTWGSCQ/52yNPP1JNTt4TOAI+NIOcAJPquadu0+etKE0u7lvb30s8/8a/WcXB0riJEZ32Iurox0ZV7EdaiLd2nmIlM6jrYbxyOuUREydvGbStH7XKd2YRtSm9o6qmKaqt6GoMjnkA5Q8U1f7itmgSukr5QIJvJSujO2vuT+f/gI+iPl/YY9KMP9vZ1+UjNmaj+xWsCO98WPI8UpGWvSY4mnrY/ZfQXjF6Beg+Z0efVgLlY6gBdRGFKhwN0ZmNugharjnLICTKogLvGVC/tuJIGQMOkSSkg5+WNrZBmWM2kRmrq6IU6InNndmsWqwlsTOcg91pD0lBOWEJMgMvB0Rxbd59PCRoGSdufRPqEmsxZOd1zlNJWW0xva9phs6tw9WIYAAgahFxQsUV4VP44xgm5kAlhCq9o6ouc6fMuSUlVAfJBGDfRPG6ew/8C81jAV91IjtD87Jf3RVYRPOu5IVE=
  api_key:
    secure: fxR4CgLAcJziTJJFvcNjkKXMeeCEBOJ/m5rNEkUU/8psVW4n2F5EcxK0gExTX33IeRTQfDaGulqYy6LVS3d2ie1dYHKiNyiYg0p5f27JHjczCDFJF9BOBQDxkoj6aR5OmFD3IJuVYRET1oj72tbeglPatBTUgOmbbfACXcT27eFW+FHRtEtju8dTpJpMXV1XKftoAj0EEY8F/lSGVuiHikqE3xiDok9HpUtmxYeMliwB4SzWTmkK9qJXcuwsoKHxuYA0P7C+/0BpbfFhd52O+yz7lnitAW15A0VB6284RAmFaw8UzPyLa4S3fvzn3Kr3VNG9erHvbQzRdChMuKzhxDKDvzrChQ6muMO0Pc1Al+OPx/cWwmqtpYOFXDORjlmMG5xOdButiVYG+ZrAxLbapu+vz+GdPcgg/BYZCXY/8aNcy9i2u2UQ15bwKzOV++qDGoGK+pYrZ9gNpdTiPNhhQ67fWTxRX/YnmWL3veq459PlWjwcd3PPjN4i0wv3SCQxHi1laaJ3aP5Z6BmC7jZ8q99qSM02vu0cuVRjQuDJ8eMJ8vQCgYn6WnesVkbLhf37ObjDKVNa0RrmlUupHrWakwRQ4VdT3jF3+gbD1XkEyyoUu4prk6Tf8evdBxn8DVlstz4Q5vmXDEwU2DjvkthywbKNzbvQ6TG1YSsreupkwNs=
  on:
    repo: wireapp/wire-webapp-cbor
    tags: true
