# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - "node"

# http://docs.travis-ci.com/user/notifications/
notifications:
  email: false

# https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - "yarn coverage"

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

# https://docs.travis-ci.com/user/deployment/npm/
deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: SXAYmPimKgyZSHm37JyEjWB3m93V5r5eDeJFJ0+hD+55ZwrcjToxtP5uX6HybeiUnvV+p2SS1yT2wr4hzIVZU6caeYKB9AcnnymCGBxcr2+HltJYMu40Gcs2N2TzLfgldJu0TjpkGK5mwyLiv7P74qzES/OBOOCkTOqJ57gbT1XlbyrZpeepqipMLZKJd6Zw6yg9c2b89gjps/t0rAE16K/v1r8qwGiG/ZSExp598UNQLS6aY4wvegJxpVZAR5AcXKk9KkeAc3nPE+Dvwh978333LvccDgeYun5imHke+MmkxlSiBhDkpbusjchKZFKTYNDIxbQeQtS6G8mavEdpKGKiYAT6oojHc2yaLNFUcoW574gL+BBEx5Rxe3oTAbQt4lQjHQH9GHi7IPqeGti9qY50L8QYKt/m2uxDEIRtcBvvEt+O0ewSQYEhB+81VEbigGLX6GD/g0A1JkZcztBVcwwOHxGvOr6etUnl7WTfOk+WBjnsFdLDaVKe9h9j4AbqQU4K80Pb61Ox/7CTv0p+XFP0KLqA1Cggr+D04NoOF6eIa+QiFR/2MeraXcLGbReHrOFKbl0fZzZ3UPJ6fWnOWW+hOuXnTRJpRxT2Yq3SuZ7ymhDL6zLrmcUi+5q3IGuXqQ0ox9JfsSO5J6UeAD0fiahtcmAWbh6HJd2ZjNWGFBI=
  api_key:
    secure: k8ONC+7YENgcvlAc4H1CUc45lf7bDVOd0G/wCjki0TdkblJ+GLzkj8JGGYClVVrPoK8BNUEJqvVANjReh6H6LJurkzO2P6n22p9lZ3MGEurv/VJoejtpQ+XelTI8NDCVpZcPVt6BOzl1Q+ooey2hQSzuG5s+/8/BYwCPva4yJCrn2D7BDC0t/PEl0ppR+aUNFJXj7R+AjqQRgM1Q+uUwiuP3pUZ4nvHXuIWvvd+epsKK3vJ2iP4Q3WGty/TKHLCJS2JHE0Y7f0M5/JLCPGE7tbXN6E+CZSs+ZEmT7cVQvCywaC4Vn4xTCpPhCKVZvZlOkxjMWEvlZT//rMIjOzqXFv9jy7y119PKy/ih1ZMZ0x7tRbPxRzlbQzxtlMthgR9kl9kFzQ6YukPz/2ij9Slc8dZbmm5n/5ok3XYd+IsdzI2BbN7STou8/WdBZU6aCXulcDXWa85f5cY6fG64eYBV2soR3oCOoe4qndUcwugI5fB651k5sEz4Ay4GcM+FShDeRZdbWWlYS5E6L/hUr9W1c9RpS8YS7gGGObk3sg1Rdfoj8lfbTMOHog1racnMAnLXgMTpYxexkUjt+tPbcxXFx7Osa6U/QRrvxyraQ9go3Fs2vC6K/Kbv76jOelhHev4rFAvvnNRwvH3S0zD3Xqvl1AS9/0KaNY0wzTFLbTtCyD4=
  on:
    tags: true
